Algoritmo "exer7"
// Disciplina   : PA
// Professora  : Edilma Bindá
// Turma   :  1ºC/TurmaB
// Nome    : Letícia Nascimento de Almeida
// Data : 25/05/2023

Var
numero:real

// ENTRADA
Inicio
escreval ("Digite um número:")
leia (numero)

//PROCESSAMENTO E SAIDA
se ((numero >100) e (numero<200)) entao
escreval (numero, " está entre 100 e 200.")
senao
escreval (numero, " não está entre 100 e 200")

fimse
Fimalgoritmo