
Algoritmo "Habilitado"
// Disciplina   : PA
// Professora  : Edilma Bindá
// Turma   :  1ºC/TurmaB
// Nome    : Letícia Nascimento de Almeida
// Data : 25/05/2023

Var
idade:real

// ENTRADA
Inicio
escreval ("Começou!")
escreval ("Informe a idade:")
leia (idade)

//PROCESSAMENTO e SAÍDA
se idade >= 18 entao
escreval("Ok,pode passar.")
senao
escreval("Você não pode dirigir!")
fimse

Fimalgoritmo