Algoritmo "exer 6"
// Disciplina   : PA
// Professora  : Edilma Bindá
// Turma   :  1ºC/TurmaB
// Nome    : Letícia Nascimento de Almeida
// Data : 25/05/2023

Var
temp:real

// ENTRADA
Inicio
escreval ("Informe a temperatura:")
leia (temp)

//PROCESSAMENTO e SAÍDA
se temp < 20 entao
escreval("Clima: FRIO!")
senao
se temp < 25 entao
escreval("Clima: NORMAL")
senao
escreval("Clima: QUENTE!")
fimse
fimse
Fimalgoritmo