Algoritmo "EXER 3"
// Disciplina   : PA
// Professora  : Edilma Bindá
// Turma   :  1ºC/TurmaB
// Nome    : Letícia Nascimento de Almeida
// Data : 25/05/2023

Var
nome: caractere
idade:real

// ENTRADA
Inicio
escreval ("Informe seu nome:")
leia (nome)
escreval ("Informe a idade:")
leia (idade)

//PROCESSAMENTO e SAÍDA
se idade >= 18 entao
escreval(nome, ", você é maior de idade.")
senao
escreval(nome, ", você é menor de idade.")
fimse

Fimalgoritmo