Algoritmo "Conversão de Celsius em Fahrenheit "
// Disciplina   : PA
// Professora   : Edilma Bindá
// Turma   : 1ºC/ B
// Nome   : Letícia Nascimento de Almeida
// Data  : 09/03/2023
Var
grausC, grausF : REAL

// ENTRADA
Inicio
escreval ("Digite uma temperatura em graus Celsius: ")
leia (grausC)

// PROCESSAMENTO
grausF <- ((9*grausC) + 160) / 5

// SAIDA
escreval (" A temperatura ", grausC, " em graus Celsius

Fimalgoritmo